name = "Super Awesome Adventure Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1270d9efa29ddc1555b9745b38c0308f02dba2a097d734a6d9b23b30f7cede1f"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20"]
