name = "Super Awesome Adventure Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd40db14b4046e90f6bb3b5183fb1004f4bc6665fffdd34dc9180eb3c704db5e"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20"]
