name = "Super Awesome Adventure Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "578e561354afbaa596d3a37a445590c6141ac30d14f8558f53d37ada086960b7"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20"]
