name = "Super Awesome Adventure Pack"
author = "ryleu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65f8ae176c55fd449fc516ea8fcaa615450bfa3a209f91e08054e99578812f89"

[versions]
minecraft = "1.20.1"
quilt = "0.20.0-beta.4"

[options]
acceptable-game-versions = ["1.20"]
